name: Build on request
on: [workflow_dispatch]

jobs:
  Windows:
    name: Build windows version
    runs-on: windows-2022
    timeout-minutes: 150

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup vcpkg and install dependencies
      shell: cmd
      run: |
        git clone https://github.com/microsoft/vcpkg C:\vcpkg-otc
        cd /d C:\vcpkg-otc
        git checkout 2022.05.10
        call .\bootstrap-vcpkg.bat
        .\vcpkg.exe install boost-iostreams:x86-windows-static boost-asio:x86-windows-static boost-beast:x86-windows-static boost-system:x86-windows-static boost-variant:x86-windows-static boost-lockfree:x86-windows-static boost-process:x86-windows-static boost-program-options:x86-windows-static boost-uuid:x86-windows-static boost-filesystem:x86-windows-static luajit:x86-windows-static glew:x86-windows-static physfs:x86-windows-static openal-soft:x86-windows-static libogg:x86-windows-static libvorbis:x86-windows-static zlib:x86-windows-static libzip:x86-windows-static bzip2:x86-windows-static openssl:x86-windows-static
        .\vcpkg.exe integrate install

    - name: Compile otclient_gl
      timeout-minutes: 30
      shell: cmd
      run: |
        cd vc16
        MSBuild /property:Configuration=OpenGL /p:PlatformToolset=v143 /p:WindowsTargetPlatformVersion=10.0 /p:BUILD_REVISION=%GITHUB_RUN_NUMBER%

    - name: Compile otclient_dx
      timeout-minutes: 30
      continue-on-error: true
      shell: cmd
      run: |
        cd vc16
        MSBuild /property:Configuration=DirectX /p:PlatformToolset=v143 /p:WindowsTargetPlatformVersion=10.0 /p:BUILD_REVISION=%GITHUB_RUN_NUMBER%

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: Download-binaries
        path: |
          otclient_gl.exe
          otclient_dx.exe
        if-no-files-found: error
